replicaCount: 5

image:
  repository: elitamsut/helloworld-expressjs
  tag: "v1.0.8"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  LISTEN_PORT: 3000
  APP_NAME: "Helloworld ExpressJS App Prod2024"
